create table if not exists public.bank_details (
  id text primary key,
  bank_name text not null,
  beneficiary_name text not null,
  iban text not null,
  account_number text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  donor_name text not null,
  donor_email text not null,
  amount numeric(12, 2) not null check (amount > 0),
  currency text not null default 'SAR',
  status text not null default 'pending' check (status in ('pending', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bank_details enable row level security;
alter table public.donations enable row level security;

drop policy if exists "Public can read bank details" on public.bank_details;
create policy "Public can read bank details"
  on public.bank_details for select to anon, authenticated using (true);

drop policy if exists "Public can insert bank details" on public.bank_details;
create policy "Public can insert bank details"
  on public.bank_details for insert to anon, authenticated with check (id = 'bank-details');

drop policy if exists "Public can update bank details" on public.bank_details;
create policy "Public can update bank details"
  on public.bank_details for update to anon, authenticated using (id = 'bank-details') with check (id = 'bank-details');

drop policy if exists "Public can insert donations" on public.donations;
create policy "Public can insert donations"
  on public.donations for insert to anon, authenticated with check (true);

drop policy if exists "Public can read donations" on public.donations;
create policy "Public can read donations"
  on public.donations for select to anon, authenticated using (true);

insert into public.bank_details (id, bank_name, beneficiary_name, iban, account_number)
values ('bank-details', 'مصرف الراجحي', 'وقف عبدالله محمد العجلان الخيري', 'SAXXXXXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXX')
on conflict (id) do nothing;
